// <auto-generated />
namespace MMA1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ClockData_Remove_SystemId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClockData_Remove_SystemId));
        
        string IMigrationMetadata.Id
        {
            get { return "201607130328025_ClockData_Remove_SystemId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
