// <auto-generated />
namespace MMA1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SystemId1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SystemId1));
        
        string IMigrationMetadata.Id
        {
            get { return "201607090238145_SystemId1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
